"""add ondelete SET NULL to user foreign keys

Revision ID: 432fc643a066
Revises: dadc766a1512
Create Date: 2026-07-21 22:30:50.286326
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '432fc643a066'
down_revision = 'dadc766a1512'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('approval_actions_actor_id_fkey'), 'approval_actions', type_='foreignkey')
    op.create_foreign_key(None, 'approval_actions', 'users', ['actor_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('approval_requests_created_by_fkey'), 'approval_requests', type_='foreignkey')
    op.create_foreign_key(None, 'approval_requests', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('audit_logs_user_id_fkey'), 'audit_logs', type_='foreignkey')
    op.create_foreign_key(None, 'audit_logs', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('journal_entries_created_by_fkey'), 'journal_entries', type_='foreignkey')
    op.create_foreign_key(None, 'journal_entries', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('stock_movements_created_by_fkey'), 'stock_movements', type_='foreignkey')
    op.create_foreign_key(None, 'stock_movements', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stock_movements', type_='foreignkey')
    op.create_foreign_key(op.f('stock_movements_created_by_fkey'), 'stock_movements', 'users', ['created_by'], ['id'])
    op.drop_constraint(None, 'journal_entries', type_='foreignkey')
    op.create_foreign_key(op.f('journal_entries_created_by_fkey'), 'journal_entries', 'users', ['created_by'], ['id'])
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.create_foreign_key(op.f('audit_logs_user_id_fkey'), 'audit_logs', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'approval_requests', type_='foreignkey')
    op.create_foreign_key(op.f('approval_requests_created_by_fkey'), 'approval_requests', 'users', ['created_by'], ['id'])
    op.drop_constraint(None, 'approval_actions', type_='foreignkey')
    op.create_foreign_key(op.f('approval_actions_actor_id_fkey'), 'approval_actions', 'users', ['actor_id'], ['id'])
    # ### end Alembic commands ###