"""add custom_tasks to users

Revision ID: 4952dfc5c852
Revises: 85d9ae31c828
Create Date: 2026-07-21 21:44:37.663075
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4952dfc5c852'
down_revision = '85d9ae31c828'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'businesses', 'super_admins', ['created_by_superadmin_id'], ['id'])
    op.add_column('users', sa.Column('custom_tasks', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'custom_tasks')
    op.drop_constraint(None, 'businesses', type_='foreignkey')
    # ### end Alembic commands ###