"""phase_7_saas_readiness

Revision ID: a907d24e2ef5
Revises: b55c4e6f8a21
Create Date: 2026-07-09 22:40:33.582167
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a907d24e2ef5'
down_revision = 'b55c4e6f8a21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Get or create default business for backfilling legacy data
    conn = op.get_bind()
    result = conn.execute(sa.text("SELECT id FROM businesses ORDER BY id LIMIT 1"))
    row = result.fetchone()
    if row:
        default_biz_id = row[0]
    else:
        # Create a default business if none exists
        from datetime import datetime, timezone
        result = conn.execute(
            sa.text("INSERT INTO businesses (name, currency, created_at) VALUES ('Default Business', 'MWK', :ts) RETURNING id"),
            {"ts": datetime.now(timezone.utc)}
        )
        default_biz_id = result.fetchone()[0]

    # Backfill NULL business_id values before making columns NOT NULL
    tables_with_business_id = [
        'bill_items', 'bills', 'customers', 'expenses', 'finished_good_outputs',
        'invoice_items', 'invoices', 'material_usages', 'payments',
        'production_batches', 'products', 'purchase_items', 'purchases',
        'receipts', 'sale_items', 'sales', 'settings', 'stock_movements',
        'stock_transactions', 'suppliers', 'users', 'warehouses',
    ]

    for table in tables_with_business_id:
        conn.execute(
            sa.text(f"UPDATE {table} SET business_id = :biz WHERE business_id IS NULL"),
            {"biz": default_biz_id}
        )

    op.create_table('plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('max_users', sa.Integer(), nullable=False),
    sa.Column('features', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('renewal_date', sa.DateTime(), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(length=255), nullable=True),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_business_id'), 'subscriptions', ['business_id'], unique=False)
    op.alter_column('bill_items', 'business_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_bill_items_business_id'), 'bill_items', ['business_id'], unique=False)
    op.create_foreign_key(None, 'bill_items', 'businesses', ['business_id'], ['id'], ondelete='CASCADE')
    op.alter_column('bills', 'business_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_bills_business_id'), 'bills', ['business_id'], unique=False)
    op.create_foreign_key(None, 'bills', 'businesses', ['business_id'], ['id'], ondelete='CASCADE')
    op.alter_column('customers', 'business_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_customers_business_id'), 'customers', ['business_id'], unique=False)
    op.create_foreign_key(None, 'customers', 'businesses', ['business_id'], ['id'], ondelete='CASCADE')
    op.alter_column('expenses', 'business_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_expenses_business_id'), 'expenses', ['business_id'], unique=False)
    op.create_foreign_key(None, 'expenses', 'businesses', ['business_id'], ['id'], ondelete='CASCADE')
    op.alter_column('finished_good_outputs', 'business_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_finished_good_outputs_business_id'), 'finished_good_outputs', ['business_id'], unique=False)
    op.create_foreign_key(None, 'finished_good_outputs', 'businesses', ['business_id'], ['id'], ondelete='CASCADE')
    op.alter_column('invoice_items', 'business_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_invoice_items_business_id'), 'invoice_items', ['business_id'], unique=False)
    op.create_foreign_key(None, 'invoice_items', 'businesses', ['business_id'], ['id'], ondelete='CASCADE')
    op.alter_column('invoices', 'business_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_invoices_business_id'), 'invoices', ['business_id'], unique=False)
    op.create_foreign_key(None, 'invoices', 'businesses', ['business_id'], ['id'], ondelete='CASCADE')
    op.alter_column('material_usages', 'business_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_material_usages_business_id'), 'material_usages', ['business_id'], unique=False)
    op.create_foreign_key(None, 'material_usages', 'businesses', ['business_id'], ['id'], ondelete='CASCADE')
    op.alter_column('payments', 'business_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_payments_business_id'), 'payments', ['business_id'], unique=False)
    op.create_foreign_key(None, 'payments', 'businesses', ['business_id'], ['id'], ondelete='CASCADE')
    op.alter_column('production_batches', 'business_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_production_batches_business_id'), 'production_batches', ['business_id'], unique=False)
    op.create_foreign_key(None, 'production_batches', 'businesses', ['business_id'], ['id'], ondelete='CASCADE')
    op.alter_column('products', 'business_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_products_business_id'), 'products', ['business_id'], unique=False)
    op.create_foreign_key(None, 'products', 'businesses', ['business_id'], ['id'], ondelete='CASCADE')
    op.alter_column('purchase_items', 'business_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_purchase_items_business_id'), 'purchase_items', ['business_id'], unique=False)
    op.create_foreign_key(None, 'purchase_items', 'businesses', ['business_id'], ['id'], ondelete='CASCADE')
    op.alter_column('purchases', 'business_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_purchases_business_id'), 'purchases', ['business_id'], unique=False)
    op.create_foreign_key(None, 'purchases', 'businesses', ['business_id'], ['id'], ondelete='CASCADE')
    op.alter_column('receipts', 'business_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_receipts_business_id'), 'receipts', ['business_id'], unique=False)
    op.create_foreign_key(None, 'receipts', 'businesses', ['business_id'], ['id'], ondelete='CASCADE')
    op.alter_column('sale_items', 'business_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_sale_items_business_id'), 'sale_items', ['business_id'], unique=False)
    op.create_foreign_key(None, 'sale_items', 'businesses', ['business_id'], ['id'], ondelete='CASCADE')
    op.alter_column('sales', 'business_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_sales_business_id'), 'sales', ['business_id'], unique=False)
    op.create_foreign_key(None, 'sales', 'businesses', ['business_id'], ['id'], ondelete='CASCADE')
    op.alter_column('settings', 'business_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_settings_business_id'), 'settings', ['business_id'], unique=False)
    op.create_foreign_key(None, 'settings', 'businesses', ['business_id'], ['id'], ondelete='CASCADE')
    op.alter_column('stock_movements', 'business_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_stock_movements_business_id'), 'stock_movements', ['business_id'], unique=False)
    op.create_foreign_key(None, 'stock_movements', 'businesses', ['business_id'], ['id'], ondelete='CASCADE')
    op.alter_column('stock_transactions', 'business_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_stock_transactions_business_id'), 'stock_transactions', ['business_id'], unique=False)
    op.create_foreign_key(None, 'stock_transactions', 'businesses', ['business_id'], ['id'], ondelete='CASCADE')
    op.alter_column('suppliers', 'business_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_suppliers_business_id'), 'suppliers', ['business_id'], unique=False)
    op.create_foreign_key(None, 'suppliers', 'businesses', ['business_id'], ['id'], ondelete='CASCADE')
    op.alter_column('users', 'business_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_users_business_id'), 'users', ['business_id'], unique=False)
    op.create_foreign_key(None, 'users', 'businesses', ['business_id'], ['id'], ondelete='CASCADE')
    op.alter_column('warehouses', 'business_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_warehouses_business_id'), 'warehouses', ['business_id'], unique=False)
    op.create_foreign_key(None, 'warehouses', 'businesses', ['business_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'warehouses', type_='foreignkey')
    op.drop_index(op.f('ix_warehouses_business_id'), table_name='warehouses')
    op.alter_column('warehouses', 'business_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_business_id'), table_name='users')
    op.alter_column('users', 'business_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'suppliers', type_='foreignkey')
    op.drop_index(op.f('ix_suppliers_business_id'), table_name='suppliers')
    op.alter_column('suppliers', 'business_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'stock_transactions', type_='foreignkey')
    op.drop_index(op.f('ix_stock_transactions_business_id'), table_name='stock_transactions')
    op.alter_column('stock_transactions', 'business_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'stock_movements', type_='foreignkey')
    op.drop_index(op.f('ix_stock_movements_business_id'), table_name='stock_movements')
    op.alter_column('stock_movements', 'business_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'settings', type_='foreignkey')
    op.drop_index(op.f('ix_settings_business_id'), table_name='settings')
    op.alter_column('settings', 'business_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'sales', type_='foreignkey')
    op.drop_index(op.f('ix_sales_business_id'), table_name='sales')
    op.alter_column('sales', 'business_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'sale_items', type_='foreignkey')
    op.drop_index(op.f('ix_sale_items_business_id'), table_name='sale_items')
    op.alter_column('sale_items', 'business_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'receipts', type_='foreignkey')
    op.drop_index(op.f('ix_receipts_business_id'), table_name='receipts')
    op.alter_column('receipts', 'business_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'purchases', type_='foreignkey')
    op.drop_index(op.f('ix_purchases_business_id'), table_name='purchases')
    op.alter_column('purchases', 'business_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'purchase_items', type_='foreignkey')
    op.drop_index(op.f('ix_purchase_items_business_id'), table_name='purchase_items')
    op.alter_column('purchase_items', 'business_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_index(op.f('ix_products_business_id'), table_name='products')
    op.alter_column('products', 'business_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'production_batches', type_='foreignkey')
    op.drop_index(op.f('ix_production_batches_business_id'), table_name='production_batches')
    op.alter_column('production_batches', 'business_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_index(op.f('ix_payments_business_id'), table_name='payments')
    op.alter_column('payments', 'business_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'material_usages', type_='foreignkey')
    op.drop_index(op.f('ix_material_usages_business_id'), table_name='material_usages')
    op.alter_column('material_usages', 'business_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.drop_index(op.f('ix_invoices_business_id'), table_name='invoices')
    op.alter_column('invoices', 'business_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'invoice_items', type_='foreignkey')
    op.drop_index(op.f('ix_invoice_items_business_id'), table_name='invoice_items')
    op.alter_column('invoice_items', 'business_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'finished_good_outputs', type_='foreignkey')
    op.drop_index(op.f('ix_finished_good_outputs_business_id'), table_name='finished_good_outputs')
    op.alter_column('finished_good_outputs', 'business_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'expenses', type_='foreignkey')
    op.drop_index(op.f('ix_expenses_business_id'), table_name='expenses')
    op.alter_column('expenses', 'business_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'customers', type_='foreignkey')
    op.drop_index(op.f('ix_customers_business_id'), table_name='customers')
    op.alter_column('customers', 'business_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'bills', type_='foreignkey')
    op.drop_index(op.f('ix_bills_business_id'), table_name='bills')
    op.alter_column('bills', 'business_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'bill_items', type_='foreignkey')
    op.drop_index(op.f('ix_bill_items_business_id'), table_name='bill_items')
    op.alter_column('bill_items', 'business_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_subscriptions_business_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_table('plans')
    # ### end Alembic commands ###