"""add customer_id and supplier_id fields

Revision ID: dadc766a1512
Revises: 4952dfc5c852
Create Date: 2026-07-21 22:22:26.115004
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dadc766a1512'
down_revision = '4952dfc5c852'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('customer_id', sa.String(length=20), nullable=True))
    op.add_column('customers', sa.Column('bank_details', sa.String(length=120), nullable=True))
    op.create_unique_constraint(None, 'customers', ['customer_id'])
    op.add_column('suppliers', sa.Column('supplier_id', sa.String(length=20), nullable=True))
    op.add_column('suppliers', sa.Column('bank_details', sa.String(length=120), nullable=True))
    op.create_unique_constraint(None, 'suppliers', ['supplier_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'suppliers', type_='unique')
    op.drop_column('suppliers', 'bank_details')
    op.drop_column('suppliers', 'supplier_id')
    op.drop_constraint(None, 'customers', type_='unique')
    op.drop_column('customers', 'bank_details')
    op.drop_column('customers', 'customer_id')
    # ### end Alembic commands ###